### ISSUE TITLE
Node red crashing with failing API request

### ISSUE THREAD

**Issue by sebster6** [energychain/node-red-contrib-discovergy-meter#115]
I'm running Home Assistant with Node Red 13.3.2 and node-red-contrib-discovergy-meter 0.7.1. This is generally working fine for many months. Unfortunately, for a couple of days now, Node Red crashes randomly (generally at least once a day) with the following log entries:

```
API Request failed:last_reading https://api.discovergy.com/public/v1/last_reading?meterId=xxx
27 Aug 12:15:37 - [red] Uncaught Exception:
27 Aug 12:15:37 - [error] Error: Error: read ECONNRESET
    at Object.last_reading (/config/node-red/node_modules/node-red-contrib-discovergy-meter/lib/discovergy.js:14:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at module.exports (/config/node-red/node_modules/node-red-contrib-discovergy-meter/lib/meter.js:58:26)
    at discovergyNode._inputCallback (/config/node-red/node_modules/node-red-contrib-discovergy-meter/DiscovergyMeter.js:28:23)
[12:15:37] WARNING: Node-RED crashed, halting add-on
[12:15:37] INFO: Node-RED stoped, restarting...
s6-rc: info: service legacy-services: stopping
[12:15:37] INFO: Node-RED stoped, restarting...
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[12:15:37] INFO: nginx stoped, restarting...
```

Unfortunately, the Addon watchdog doesn't seem to successfully restart Node Red, and I only find out about it having crashed again when the energy meter sensor doesn't change anymore. :(
Is there anything you can do in regards to error handling? I changed my frequency of API calls from every 10 seconds to only every 30 seconds, but it doesn't seem to change anything.

**Comment by zoernert** [comment]
Hi Sebastian,

I could ignore the connection reset (which is not error handling...)
however I saw connection resets in my Installation too and forwarded this
case to ***@***.***

Could you open a Request in the Discovergy forum too?

Sebastian ***@***.***> schrieb am So., 28. Aug. 2022, 15:42:

**Comment by zoernert** [comment]
Should be fixed with https://github.com/energychain/node-red-contrib-discovergy-meter/commit/733e57850ddf9a953e3d82d82ba72046da1e8dda
