### ISSUE TITLE
Node Red crashes when trying to configure login parameters

### ISSUE THREAD

**Issue by McTristan** [energychain/node-red-contrib-discovergy-meter#5]
Whenever I try to configure the login parameters node red always crashes and goes into a boot loop.
I can only resolve the problem by running node red in safe mode + removing the configuration node :(

I'm using the latest Node Red version in Docker on a Ubuntu 20.4 host. I can reproduce the issue everytime.

Here is the stacktrace:

at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12)
at /opt/iobroker/node_modules/express/lib/router/index.js:281:22
at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
at Route.dispatch (/opt/iobroker/node_modules/express/lib/router/route.js:112:3)
at next (/opt/iobroker/node_modules/express/lib/router/route.js:137:13)
at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
at /opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-discovergy-meter/DiscovergyMeter.js:64:34
at ServerResponse.send (/opt/iobroker/node_modules/express/lib/response.js:170:12)
at ServerResponse.header (/opt/iobroker/node_modules/express/lib/response.js:771:10)
at ServerResponse.setHeader (_http_outgoing.js:518:11)
(4915) Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
(4915) unhandled promise rejection: Cannot set headers after they are sent to the client

**Comment by McTristan** [comment]
It works - kind of. When it crashes and restarts in save-Mode, you must configure at least one configuration node. Red node crashes when trying to open the username/password dialog but once you have entered the correct values & deploy your changes it seems to be stable.
I don't think it should be like that ... I've tested 0.6.1 and 0.6.6 - both have the same behavior.

**Comment by zoernert** [comment]
Ok, I will have a Look. Do you get a list of meters on your available to your account in safe Mode?

**Comment by McTristan** [comment]
After redeploying: yes. I can select the meter and use the node from then on. However: when I create a new configuration node it starts to break again until I have (in safe mode) setup the configuration with the correct credentials.
Red node also doesn't like it when I forget to put the right values in the meter node - it crashes as soon as I put it onto my flow - but being in safe mode I can also fix it. From then on it works and never crashes again (once you have figured out what the different settings are -> a better description would be great).

**Comment by zoernert** [comment]
Should be fixed [0.6.7](https://github.com/energychain/node-red-contrib-discovergy-meter/releases/tag/0.6.7) (at least on my test deployments). 

Thanks for reporting!

Please test and confirm on your deployment.
