### ISSUE TITLE
Node red crashes when not selecting a meter in the "Meter" and "Production Meter" section of the "DiscovergyMeter" node

### ISSUE THREAD

**Issue by McTristan** [energychain/node-red-contrib-discovergy-meter#6]
Thank you for updating the module and fixing the "node red crashes when configuration is not complete" issue. However, I'm experiencing also "node red crashing" issues with the DiscovergyMeter node when not selecting a meter in the "Meter" and "Production Meter" node.

When I add the node and select only one combobox entry (i.e. "Meter") and deploy the node, node red crashes. It looks like there should be some additional checks to prevent this. The same happens when I have not yet configured the discovergy account though I can live with that.

Keep up the great work and sorry for not answering your last question but I'm really busy.

**Comment by zoernert** [comment]
solved after #73
