### ISSUE TITLE
Security vulnerability in axois v0.19.2

### ISSUE THREAD

**Issue by schmiegelt** [energychain/node-red-contrib-discovergy-meter#68]
When trying to install this node, I got an error message, that in axios v0.19.2 there is a critical security vulnerability. An update to v0.21.1 is strongly suggested.
It might be due to some other settings I have, but node red is refusing to start with this critical vulnerability.

PR #66 is already opened, and I'd appreciate if it could be merged.

Reference:
https://github.com/axios/axios/pull/3410

**Comment by zoernert** [comment]
Updated - sorry due to another issue I haven't used the PR as base but will accept it now. 

it is 0.24 now.
