### ISSUE TITLE
No statistics data delivered anymore 

### ISSUE THREAD

**Issue by sebster6** [energychain/node-red-contrib-discovergy-meter#69]
I'm using node-red-contrib-discovergy-meter in my Home Assistant installation, getting the data from my Discovergy meter.
This was running fine in the last couple of months (I have a default call every 10 seconds to get the current power information, and a "statistics" call every 5min to get additional information). Unfortunately, since a couple of weeks the call with the "statistics" option as a topic doesn't deliver data anymore :(
I'm not sure whether something on the Discovergy API side changed, or if anything else broke. Unfortunately, debug logs don't show me anything useful (or I don't know where exactly to look). I already deleted the palette and set up everything again, but to no avail. Any help is greatly appreciated.

Working fine:
<img width="845" alt="Bildschirmfoto 2021-11-25 um 11 48 18" src="https://user-images.githubusercontent.com/9269030/143428220-402c4681-bde6-49ef-b63a-ce84fcd832ec.png">

No results:
<img width="940" alt="Bildschirmfoto 2021-11-25 um 11 48 30" src="https://user-images.githubusercontent.com/9269030/143428228-ee9fb1fb-280f-4828-9de9-d175ab412dcb.png">

**Comment by phunkybeam** [comment]
Have your flow also recently implemented in my HomeAssistant the current data comes in. Statistics data also do not arrive with me :-(

And I thought I had done something wrong or it needs an extended activation by Discovergy.

**Comment by zoernert** [comment]
For this Node-RED module (Node) the issue was a simple update of dependencies and a side effect caused in a "null" check. Should be fixed in v0.6.9 which got just published (as #74). Please validate and report back.

**Comment by sebster6** [comment]
Thanks for taking care of the issue, much appreciated!

While reloading NodeRed multiple times and waiting for 0.6.9 in the palette (it's not showing there yet), suddenly values are now coming in again:
<img width="553" alt="Bildschirmfoto 2021-12-08 um 21 24 00" src="https://user-images.githubusercontent.com/9269030/145279115-d3f8c40f-e30f-46b4-8a6d-d6ba3408ba3c.png">

So the weird thing is, the palette is showing me I'm still running 0.6.8, and I haven't updated anything.

**Comment by sebster6** [comment]
Update to 0.6.9 now went through and I can confirm everything's working well. Thanks!
