### ISSUE TITLE
Pulling data from demo meter?

### ISSUE THREAD

**Issue by PolyGONtrauma** [energychain/node-red-contrib-discovergy-meter#72]
I am having problems getting correct data from my Smart Meter. 
First I have set up the discovergy-config node correctly with my Discovergy login data. Using those credentials in the Discovergy Meter node seems to work, it shows my correct Meter ID after deploying.
But when injecting the Discovergy Meter node, I only get data from another meter, which seems to be a Corrently Demo Meter (meterID: "781ffa307e434529be9f747eece1b8dc"), while in my Discovergy Meter node the correct meter is shown.
Running node-red (version 2.1.3) within Home Assistant on a RPi4.
Using "node-red-contrib-discovergy-meter" version 0.6.9.

**Comment by zoernert** [comment]
How many meters do you have listed on your account? Do you have this issue (Demo Meter used) with all of them?

Assuming that you retrieved the `meterId` from `msg.payload.meterinfo` ?

**Comment by PolyGONtrauma** [comment]
I only have one meter in my account.
Yes, I retrieved the meterID from msg.payload.meterinfo.
Is there anything I can do/check to get behind the problem?!

**Comment by PolyGONtrauma** [comment]
For test purposes I just installed Node-Red on windows directly, imported my flow, and here it works, it pulls data from my real meter. So maybe my problem is not the discovergy node, but something with my Node-Red installation in HomeAssistant?!

**Comment by zoernert** [comment]
_ So maybe my problem is not the discovergy node, but something with my Node-Red installation in HomeAssistant?!_

We will figure it out. HA is installed on a RPi? - Could you check the Node JS Version (and compare with your Windows installation)?  If possible, try to make bot equal. 

In case this is the issue, I will try to solve it in the code.

**Comment by PolyGONtrauma** [comment]
After reinstalling Homeassistant and NodeRed it finally works, so it probably was caused by a faulty setup. Thanks for your help! :)
